### ISSUE TITLE
README.md file not helping for me

### ISSUE THREAD

**Issue by yashwanthbabu** [shaydesdsgn/SDF-NSTextField-Validation#1]
Hi.

I need to use this for my mac application. You dont have given any installation instructions to use this.
Please update the installation instructions so that i can use this in my code

Thanks

**Comment by trentmilton** [comment]
Installation is pretty standard. Just drop the files into Xcode and import the header in the README.md

**Comment by yashwanthbabu** [comment]
Is this a Objective-C related or Swift Related?

**Comment by trentmilton** [comment]
This is Objective-c code. I'm happy to help if you have problems running the code, i.e. bugs, but from your questions it sounds like you haven't spent any time trying to use the code. In which case please spend some time trying the code before posting questions about it like this one. In future I might look at putting in a sample project but I assumed that as it's a simple class anyone looking to use it would understand how to import and implement it even without the README I've provided.

**Comment by trentmilton** [comment]
I haven't heard anything more about this so I'm assuming it's all good.
